version: "3.8"

services:
  evolution-api:
    image: atendai/evolution-api:latest
    container_name: evolution_api
    restart: ${DOCKER_RESTART_POLICY}
    ports:
      - "${WA_PORT}:8080"
    environment:
      # This pulls from your .env
      - AUTHENTICATION_API_KEY=${WA_API_KEY}
      - WABROWSER_BROWSER=Chrome
      - LOG_LEVEL=ERROR
    volumes:
      # This ensures you don't have to scan the QR code every time you restart
      - evolution_instances:/evolution/instances

volumes:
  evolution_instances:
